# Generated by Django 4.2.2 on 2023-06-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_main',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orderprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type', models.PositiveIntegerField(choices=[(0, '單點主餐'), (1, '便當'), (2, '湯品'), (3, '小菜類'), (4, '飲料類')])),
                ('prod_no', models.PositiveIntegerField()),
                ('prod_nam', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Price_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_price', models.IntegerField()),
                ('prod_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='APP_orderMV.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pid', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('each_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_ID', to='APP_orderMV.order_main')),
            ],
        ),
    ]
