# Generated by Django 4.2.2 on 2023-06-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.IntegerField()),
                ('order_state', models.CharField(choices=[('0', '內用'), ('1', '外帶')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type', models.CharField(choices=[('0', '單點主餐'), ('1', '便當'), ('2', '湯品'), ('3', '小菜類'), ('4', '飲料類')], max_length=5)),
                ('prod_no', models.CharField(max_length=5)),
                ('prod_id', models.CharField(editable=False, max_length=10)),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('each_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_ID', to='APP_orderMV.order_main')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_ID', to='APP_orderMV.products')),
            ],
        ),
    ]
