# Generated by Django 4.2.2 on 2023-06-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_main',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Price_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=5)),
                ('num', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nam', models.CharField(max_length=30)),
                ('pord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orderMV.price_table')),
            ],
        ),
        migrations.CreateModel(
            name='Order_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_ID', to='APP_orderMV.order_main')),
            ],
        ),
    ]
